/:
  controller: Main
  action: index

/blog/:category:
  controller: Main
  action: indexByCategory

/post/:id:
  controller: Posts
  action: show

/comment:
  controller: Comments
  action: store

/dashboard/comments/edit/:id:
  controller: Comments
  action: edit

/dashboard/comments/update/:id:
  controller: Comments
  action: update

/dashboard/comments/delete/:id:
  controller: Comments
  action: delete

/dashboard:
  controller: Main
  action: dashboard

/dashboard/users:
  controller: Users
  action: index

/dashboard/posts:
  controller: Posts
  action: index

/dashboard/comments:
  controller: Comments
  action: index

/dashboard/categories:
  controller: Categories
  action: index

/contact:
  controller: Main
  action: contact

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/verify:
  controller: Security
  action: verifyEmail

/dashboard/users/create:
  controller: Users
  action: create

/dashboard/users/store:
  controller: Users
  action: store

/dashboard/users/edit/:id:
  controller: Users
  action: edit

/dashboard/users/update/:id:
  controller: Users
  action: update

/dashboard/users/delete/:id:
  controller: Users
  action: delete

/dashboard/categories/create:
  controller: Categories
  action: create

/dashboard/categories/store:
  controller: Categories
  action: store

/dashboard/categories/edit/:id:
  controller: Categories
  action: edit

/dashboard/categories/update/:id:
  controller: Categories
  action: update

/dashboard/categories/delete/:id:
  controller: Categories
  action: delete

/dashboard/posts/create:
  controller: Posts
  action: create

/dashboard/posts/store:
  controller: Posts
  action: store

/dashboard/posts/edit/:id:
  controller: Posts
  action: edit

/dashboard/posts/update/:id:
  controller: Posts
  action: update

/dashboard/posts/delete/:id:
  controller: Posts
  action: delete
